/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;


import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Joaquin
 */
public class AgregarAnimal extends javax.swing.JFrame {
    /**
     * Creates new form AgregarAnimal
     */
    public AgregarAnimal() {
        initComponents();
        herbivoroPanel.setVisible(false);
        cambiarSectores(data.Persistencia.getSectoresCarnivoro());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        extraText = new javax.swing.JTextField();
        sectorBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        agregarAnimal = new javax.swing.JButton();
        volverButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nombreText = new javax.swing.JTextField();
        origenText = new javax.swing.JTextField();
        edadText = new javax.swing.JTextField();
        pesoText = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        alimenBox = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        codIso = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        extraText1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        herbivoroPanel = new javax.swing.JPanel();
        valorFijoText = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        extraText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        extraText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extraTextActionPerformed(evt);
            }
        });
        getContentPane().add(extraText, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 110, -1));

        sectorBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sectorBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        getContentPane().add(sectorBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 110, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Agregar animal");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 430, 10));

        agregarAnimal.setBackground(new java.awt.Color(51, 204, 0));
        agregarAnimal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        agregarAnimal.setText("Agregar animal");
        agregarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAnimalActionPerformed(evt);
            }
        });
        getContentPane().add(agregarAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 430, 400, -1));

        volverButton.setBackground(new java.awt.Color(0, 102, 255));
        volverButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        volverButton.setText("Volver");
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });
        getContentPane().add(volverButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Nombre especie:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 120, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Alimentacion:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 100, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Pais de origen:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 120, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Edad:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 90, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Peso:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 90, 30));

        nombreText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(nombreText, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 110, -1));

        origenText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        origenText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                origenTextActionPerformed(evt);
            }
        });
        getContentPane().add(origenText, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 110, 30));

        edadText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        edadText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadTextActionPerformed(evt);
            }
        });
        getContentPane().add(edadText, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 110, -1));

        pesoText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pesoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoTextActionPerformed(evt);
            }
        });
        getContentPane().add(pesoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 110, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 430, 10));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 430, 10));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 430, 10));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 430, 10));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 10, 500));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 10));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Sector:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 90, 30));

        alimenBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        alimenBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carnivoro", "Herbivoro" }));
        alimenBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                alimenBoxItemStateChanged(evt);
            }
        });
        getContentPane().add(alimenBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 110, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Extra:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 90, 30));

        codIso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        codIso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codIsoActionPerformed(evt);
            }
        });
        getContentPane().add(codIso, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 110, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Codigo ISO:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 90, 30));

        extraText1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        extraText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extraText1ActionPerformed(evt);
            }
        });
        getContentPane().add(extraText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 110, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Extra:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 90, 30));

        herbivoroPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valorFijoText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        valorFijoText.setText("0");
        valorFijoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorFijoTextActionPerformed(evt);
            }
        });
        herbivoroPanel.add(valorFijoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 110, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Valor fijo:");
        herbivoroPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        getContentPane().add(herbivoroPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 210, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void extraTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extraTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_extraTextActionPerformed

    private void origenTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_origenTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_origenTextActionPerformed

    private void edadTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadTextActionPerformed

    private void pesoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoTextActionPerformed

    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed
        this.setVisible(false);
        Principal view = new Principal();
        view.setVisible(true);
    }//GEN-LAST:event_volverButtonActionPerformed

    private void agregarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAnimalActionPerformed
    int s;
    double val;
    try {
        s = Integer.parseInt((String)sectorBox.getSelectedItem());
        val= Double.parseDouble(valorFijoText.getText().trim());
        Controlador.agregarAnimalNuevo(nombreText,origenText,pesoText,alimenBox,s,extraText,edadText,codIso,val);   
        } catch (NumberFormatException e) {
        throw new IllegalArgumentException("El número de sector debe ser un valor entero.");
    }
    }//GEN-LAST:event_agregarAnimalActionPerformed

    private void codIsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codIsoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codIsoActionPerformed

    private void alimenBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_alimenBoxItemStateChanged
         if (evt.getStateChange() == ItemEvent.SELECTED) {
                    String seleccionado = (String) evt.getItem();
                    if ("Herbivoro".equals(seleccionado)) {
                        herbivoroPanel.setVisible(true);
                        cambiarSectores(data.Persistencia.getSectoresHerbivoro());
                    }
                    if("Carnivoro".equals(seleccionado)){
                        herbivoroPanel.setVisible(false);
                        cambiarSectores(data.Persistencia.getSectoresCarnivoro());
                    }
        }
    }//GEN-LAST:event_alimenBoxItemStateChanged

    private void extraText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extraText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_extraText1ActionPerformed

    private void valorFijoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorFijoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorFijoTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarAnimal;
    private javax.swing.JComboBox<String> alimenBox;
    private javax.swing.JTextField codIso;
    private javax.swing.JTextField edadText;
    private javax.swing.JTextField extraText;
    private javax.swing.JTextField extraText1;
    private javax.swing.JPanel herbivoroPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField nombreText;
    private javax.swing.JTextField origenText;
    private javax.swing.JTextField pesoText;
    private javax.swing.JComboBox<String> sectorBox;
    private javax.swing.JTextField valorFijoText;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables

    private void cambiarSectores(String[] sectores) {
    sectorBox.removeAllItems(); // Limpia los anteriores

    for (String s : sectores) {
        sectorBox.addItem(s);
    }
    }
}
